### ISSUE TITLE
Initial draft

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston_window#1]
This window back-end will do things a bit differently than what we have done until now. For example, we can pass an `Rc<RefCell<GlutinWindow>>` with all events and the same for Gfx device and resources. This means that the handler of an event has access to the window and resource creation through a single argument.

**Comment by bvssvni** [comment]
We might need to change piston-event a bit to support this. For example, `MouseCursorEvent::from_xy(x, y)` need an argument of the old event, which will clone the references.

```Rust
let e = MouseCursorEvent::from_xy(x, y, e);
```

This is not a problem, because whenever you remap events, for example in ai_behavior, you are already handling an event.

**Comment by bvssvni** [comment]
The `PistonWindow` should be both an event wrapper, an event iterator and a window.

**Comment by Potpourri** [comment]
How we do wrappers, it means that `piston_window` will be dependent and from `gfx` and from `glium`?

**Comment by Potpourri** [comment]
Ahh, this only for `gfx` right?

**Comment by bvssvni** [comment]
Yes.

**Comment by bvssvni** [comment]
I'll open another discussion for Gfx.
