### ISSUE TITLE
How do I write the concrete type of a Texture?

### ISSUE THREAD

**Issue by bachm** [PistonDevelopers/piston_window#111]
```
extern crate piston_window;

use piston_window::*;

fn main() {
    use std::path::Path;
    
    let window: PistonWindow = WindowSettings::new("Test", (1024, 768))
        .exit_on_esc(true)
        .build()
        .expect("failed to create window");
    
    let ref settings = TextureSettings::new();
    
    let t: Texture<piston_window::gfx_device_gl::Resources> = Texture::from_path(&mut *window.factory.borrow_mut(), Path::new("assets/texture.png"), Flip::None, settings).unwrap();
```

The type should be `Texture<piston_window::gfx_device_gl::Resources>` according to my understanding but since `Resources` is private the compiler cannot resolve this path.

Trying to use `Resources` from a separate `gfx_device_gl` crate results in an error message about two separate crate versions being used.

Am I missing something obvious or is it really impossible to specify the concrete type of a Texture?

**Comment by mitchmindtree** [comment]
@bachm hmm it might just be that `Resources` was intended to be exported from the piston_window crate but hasn't yet? It seems like piston_window could even export an alias for that type you're trying to write (i.e. `GlTexture = Texture<gfx_device_gl::Resources>`, just like how `Glyphs` and `GfxStream` are aliases). 

Come to think of it, you could probably use the concrete texture type via the Graphics' associated type, i.e.

```rust
let t: <G2d as Graphics>::Texture = Texture::from_path(&mut *window.factory.borrow_mut(), Path::new("assets/texture.png"), Flip::None, settings).unwrap();
```

You might even just be able to write the type as `G2d::Texture` but i'm not 100% certain.

In any case, @bvssvni will probably be able to recommend the right way to you.

**Comment by TheNeikos** [comment]
What I did was to import the `gfx_device_gl` crate with the *exact* same version as `piston_window` uses. Right now that is: 0.7

**Comment by bachm** [comment]
This compiles, so it's possible to get this working. It could be simpler though.

```
struct Player {
    tex: <G2d<'static> as Graphics>::Texture
} 

fn main() {
    use std::path::Path;
    
    let window: PistonWindow = WindowSettings::new("Test", (1024, 768))
        .exit_on_esc(true)
        .build()
        .expect("failed to create window");
        
        
    let p = Player {
        tex: Texture::from_path(&mut *window.factory.borrow_mut(), Path::new("assets/texture.png"), Flip::None, &TextureSettings::new()).unwrap()
    }; 

}
```
