### ISSUE TITLE
Redesign to use `while let`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston_window#123]
Some people are complaining about the `Rc<RefCell<T>>` usage in this library.

Since the Piston core now uses `while let`, it might be possible to do the same here.

**Comment by mitchmindtree** [comment]
:+1: This would be super nice!

**Comment by TheNeikos** [comment]
@bvssvni Do you have a link for that? I would like to check it out. (Tried to google a bit, but slow internet + not sure what exactly to put in made it fruitless)

I'm curious how `while let` and `Rc<RefCell<T>>` play together

**Comment by mitchmindtree** [comment]
@TheNeikos the `while let` pattern can allow for "iteration" that doesn't borrow the "iterator" (without using an actual `Iterator` type) i.e:

```rust
while let Some(event) = events.next_event(&mut window) {
    // Here we still have unique access to the `Window` and `events`
}
```

**Comment by mitchmindtree** [comment]
@TheNeikos here's the [recently updated `next` method](https://github.com/PistonDevelopers/piston/blob/master/src/event_loop/src/lib.rs#L153) that @bvssvni mentioned.

**Comment by TheNeikos** [comment]
That means it would be possible to access the various states as references directly instead of using `Rc`s ? (It seems so, but perhaps I'm forgetting something)

**Comment by mitchmindtree** [comment]
@TheNeikos I don't know @bvssvni's plans for certain, bus yes it should enable us to do so :+1:

**Comment by zmoshansky** [comment]
Exciting! This would be really helpful to get access to `window.factory` in the event loop so that images/fonts can be loaded up on demand. Unless I'm missing something where that's already possible? (I keep getting error: use of moved value: `window.factory`, and I haven't seen an example that does it.)

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/piston_window/pull/130
