### ISSUE TITLE
Cannot clear window due to `draw_*d` being on the window now

### ISSUE THREAD

**Issue by TheNeikos** [PistonDevelopers/piston_window#136]
An unforseen consequence of putting the draw on the window is that it is now borrowed mutably during `draw_2d` and `draw_3d`! Which means that one cannot now borrow anything from it immutably, like for example clearing the output.

```rust
window.draw_3d(&e, |enc| {
    enc.clear(&window.output_color, GRAY);
});
```

Will not compile.

(I've accidentally opened it on the wrong [repo](https://github.com/PistonDevelopers/piston-examples/issues/345) before )

**Comment by mitchmindtree** [comment]
One option could be to make new types `Draw2d` and `Draw3d` (or `Draw2dArgs` and `Draw3dArgs`) which could be passed to their respective closures as the sole argument. These types could encapsulate both the fields from the `window` that a user might deem necessary, along with all current arguments. I.e.

```rust
window.draw_3d(&e, |args| {
    args.enc.clear(&args.output_color, GRAY);
})
```

Another nice quality of wrapping args in a struct is that you can destructure them in argument position:

```rust
window.draw_3d(&e, |Draw3d { ref mut enc, output_color }| {
    enc.clear(output_color, GRAY);
})
```

**Comment by bvssvni** [comment]
Alternative:

- Pass `PistonWindow` to `draw_3d`
- Remove `PistonWindow::app` to use application state separately in `draw_2d`

**Comment by bvssvni** [comment]
I've opened a PR https://github.com/PistonDevelopers/piston_window/pull/138 for the alternative I suggested. It does what @mitchmindtree suggested for `draw_3d`, and the overall design gets simpler. I prefer this to adding more complexity, and it keeps 2D rendering consistent with the other graphics backends.
