### ISSUE TITLE
Wait for event instead of polling

### ISSUE THREAD

**Issue by antoyo** [PistonDevelopers/piston_window#144]
Hello.
In the examples, I saw that events are polled:

``` rust
fn main() {
    let mut window: PistonWindow = WindowSettings::new("Hello World!", [512; 2]).build().unwrap();
    while let Some(event) = window.next() {
    }
}
```

I wonder if there is a way to wait for an event to avoid looping many times for nothing.

For instance, if I want to wait for a key press for an input text widget, I don't need to loop at all.

So, what can I do to wait for an event?

Thanks for your help.

**Comment by bvssvni** [comment]
The Piston game loop does not wait for events.

**Comment by antoyo** [comment]
Having something like `SDL_WaitEvent`  would be useful to avoid using the CPU for nothing.

For instance, `conrod` would benefit from having a wait event function. A `conrod` application uses 100% CPU even when there is no events/screen updates.

Should I open an issue on the piston project instead?

Thanks.

**Comment by bvssvni** [comment]
If Conrod uses 100%, then it is probably because you use `draw` instead of `draw_if_changed`.

**Comment by antoyo** [comment]
That was only an example found in the conrod repository.

The following example that uses only `piston_window` uses 2-3% CPU for nothing:

```rust
extern crate piston;
extern crate piston_window;

use piston::input::{Button, Key, PressEvent, ResizeEvent, TextEvent};
use piston::window::Window;
use piston_window::{PistonWindow, WindowSettings, clear, rectangle};

fn main() {
    let mut window: PistonWindow = WindowSettings::new("Hello World!", [512; 2]).build().unwrap();
    while let Some(event) = window.next() {
        //println!("Event");
        if let Some(Button::Keyboard(key)) = event.press_args() {
            if key == Key::Escape {
                window.set_should_close(true);
            }
        }

        event.text(|text| println!("Typed: {}", text));

        event.resize(|width, height| println!("Resized: {}, {}", width, height));

        window.draw_2d(&event, |context, graphics| {
            clear([0.5, 0.5, 0.5, 1.0], graphics);
            rectangle([1.0, 0.0, 0.0, 1.0], [0.0, 0.0, 100.0, 100.0], context.transform, graphics);
        });
    }
}
```

If we uncomment the `println` line, we see that it prints text many many times.

What's wrong in this example (what causes this CPU usage and what to do to avoid it?)?

Is there a way to wait for an event using `piston`?

Thanks for your help.

**Comment by bvssvni** [comment]
The piston_window crate is meant for easy setup, while the Piston core should be used directly when more flexibility is required. See discussion https://github.com/PistonDevelopers/piston/issues/1109. Example that uses the core: https://github.com/PistonDevelopers/piston-examples/blob/master/user_input/src/main.rs. The core has no direct support for waiting events, perhaps we should add that?

**Comment by bvssvni** [comment]
Closing because you can now use `EventSettings::lazy`.
