### ISSUE TITLE
Update to gfx version 0.12

### ISSUE THREAD

**Issue by joelwkall** [PistonDevelopers/piston_window#154]
I'm trying to get gfx_text working with piston_window (see [gfx_text PR #47 ](https://github.com/PistonDevelopers/gfx_text/pull/47#issuecomment-229927978) and [piston_window issue #153](https://github.com/PistonDevelopers/piston_window/issues/153))

It seems that we need to update the gfx dependency of piston_window to 0.12. Would that be much work?

**Comment by bvssvni** [comment]
[Eco](https://github.com/pistondevelopers/eco) will tell you how much work it is and what to do. Run `cargo run --example piston > todo.txt`.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/piston_window/pull/155
