### ISSUE TITLE
G2dTexture alias lifetime

### ISSUE THREAD

**Issue by AndyBarron** [PistonDevelopers/piston_window#173]
Is there a reason `G2dTexture` is defined as `G2dTexture<'a>`? The lifetime makes it way less ergonomic (to the point where I added `gfx_device_gl` to my dependencies just to make a more convenient type alias).

AFAICT, we could get rid of the lifetime without any side effects (other than potential code breakage, but I think that's fine for `0.x` -> `0.y` updates).

**Comment by radix** [comment]
I ran into this too, and I see that all code I can find in the internet (actually just conrod) explicitly uses `'static` as the lifetime parameter, probably because it's meaningless.

**Comment by radix** [comment]
Thank you very much @bvssvni!
