### ISSUE TITLE
Rendered text is blurry

### ISSUE THREAD

**Issue by vvilhonen** [PistonDevelopers/piston_window#179]
Running [hello world from piston-examples](https://github.com/PistonDevelopers/piston-examples/blob/master/src/hello_world.rs) results in blurry text on mac os 10.12 macbook retina display. Here's a screenshot of background changed to white and text to black using size 16.

<img width="205" alt="fuzzy3" src="https://cloud.githubusercontent.com/assets/88401/21661574/f848f5fc-d2d4-11e6-9510-38b7bedbf265.png">

**Comment by bvssvni** [comment]
To fix the blurry one can set `TextureSettings::new().min(Filter::Nearest)`.

Closing.

**Comment by inDigiNeous** [comment]
> To fix the blurry one can set `TextureSettings::new().min(Filter::Nearest)`.
> 
> Closing.

Set where ? Can you be more specific ? Thanks.

**Comment by ffactory-ofcl** [comment]
@inDigiNeous and to anyone coming here:
instead of declaring my glyphcache the easy way:
`
    let mut glyphs = window
        .load_font("assets/imagine.ttf")
        .expect("Failed to load font.");
`
I used
`let mut glyphs = Glyphs::new(
        "assets/imagine.ttf",
        TextureContext {
            factory: window.factory.clone(),
            encoder: window.factory.create_command_buffer().into(),
        },
        TextureSettings::new().min(Filter::Nearest).mag(Filter::Nearest,
    )
    .expect("Failed to load font!");
`
