### ISSUE TITLE
Bug when migrating from 0.63 to 0.64

### ISSUE THREAD

**Issue by aochagavia** [PistonDevelopers/piston_window#186]
I maintain the [Rocket](https://github.com/aochagavia/rocket) game and am facing a bug when rendering "explosions" (which are just a bunch of ellipses). When you shoot an enemy, 300 purple ellipses are generated to simulate an explosion.

After updating the dependencies (see https://github.com/aochagavia/rocket/pull/56), the ellipses don't get rendered properly, in a way that resembles screen tearing (though I am not sure it is exactly the same). I tried recording a video using FRAPS, but for some reason the graphics in the video don't match what gets rendered on the screen. Maybe the best way to triage this is by playing the game yourself to see what I mean.

By the way, Rocket is just a toy project so this is not urgent at all (at least for me)

**Comment by bvssvni** [comment]
Thanks for reporting. Will have a look.

**Comment by bvssvni** [comment]
There was a redesign in piston-graphics that changed how coordinates are encoded in the slice sent to the backend. It could have something to do with that.

**Comment by bvssvni** [comment]
This bug appears in both 0.63 and 0.64. It might not be related to updating version?

By adding `let mut speed = 1.0;` before the loop and controlling it with W/S (multiply or divide by 1.1), I was able to slow down the game so I could make screenshots of the bug:

![screen shot 2017-02-27 at 19 12 40](https://cloud.githubusercontent.com/assets/1743862/23373722/878d3176-fd21-11e6-85b1-20606cf0a168.png)

![screen shot 2017-02-27 at 19 13 32](https://cloud.githubusercontent.com/assets/1743862/23373733/91ab9404-fd21-11e6-8863-18d616755fb8.png)

![screen shot 2017-02-27 at 19 13 09](https://cloud.githubusercontent.com/assets/1743862/23373728/8bc7cc24-fd21-11e6-9ea0-eaacae9144bf.png)

These screenshots were taken with:

```
piston_window = "0.63.0"
piston2d-opengl_graphics = "0.39.0"
```

**Comment by bvssvni** [comment]
Btw, I recommend just using the Piston core with opengl_graphics, since you do not need all the gfx stuff that piston_window sets up.

**Comment by bvssvni** [comment]
Tried an older version and the bug disappeared:

```
piston_window = "0.60.0"
piston2d-opengl_graphics = "0.36.2"
```

**Comment by bvssvni** [comment]
I suspect there is a bug in the buffer code in opengl_graphics.

**Comment by aochagavia** [comment]
@bvssvni What do you mean by "using the Piston core with opengl_graphics"? Which crates should I use?

**Comment by bvssvni** [comment]
I meant using the "piston" create + "pistoncore-glutin_window". The setup is almost identical.

Here is an example: https://github.com/PistonDevelopers/opengl_graphics/blob/master/examples/image_test.rs

**Comment by bvssvni** [comment]
Another thing: I see you use the `ellipse` shortcut: https://github.com/aochagavia/rocket/blob/master/src/models/bullet.rs#L25

This uses the default resolution 128 which is very high https://github.com/PistonDevelopers/graphics/blob/master/src/ellipse.rs#L36.

You might want change to using the `Ellipse` object directly and set the resolution to a lower number, e.g. 16 or 32.

**Comment by bvssvni** [comment]
Fixed by https://github.com/PistonDevelopers/opengl_graphics/pull/271

Change piston2d-opengl_graphics to 0.42.1.

Closing.

**Comment by aochagavia** [comment]
Great! Thanks!

**Comment by johnthagen** [comment]
Thanks @bvssvni we were seeing a similar issue in [rust-belt](https://github.com/johnthagen/rust-belt). Will update to piston2d-opengl_graphics to 0.42.1
