### ISSUE TITLE
more examples, better documentation

### ISSUE THREAD

**Issue by jaroslaw-weber** [PistonDevelopers/piston_window#195]
Its hard to work with piston_window without proper documentation and more examples. I had lot of troubles with displaying single image, recently struggling with input.

**Comment by bvssvni** [comment]
See the README of https://github.com/PistonDevelopers/piston.

I believe there are many people visiting this repository first and get stuck.

**Comment by jaroslaw-weber** [comment]
still, if the window repo is a wrapper it would be nice to have it explained here with links to other repos

**Comment by bvssvni** [comment]
Just added a link https://github.com/PistonDevelopers/piston_window/blob/master/README.md

**Comment by jaroslaw-weber** [comment]
i would go with bigger bolder font for the link, to make people focus when they first see the repo.
thanks for good work btw :)

**Comment by bvssvni** [comment]
Closing.
