### ISSUE TITLE
Incorrect output height and width

### ISSUE THREAD

**Issue by dmitry-egorov** [PistonDevelopers/piston_window#22]
I've ran into a problem when running gfx-cube example from [piston examples] (https://github.com/PistonDevelopers/piston-examples) on a mac.
![screen shot 2015-05-10 at 06 02 01](https://cloud.githubusercontent.com/assets/5902807/7552886/7424f3c0-f6da-11e4-942e-a11c16d1fca7.png)

As you can see, height and width of the output are halved. I've ran into similar problem with [this example] (https://github.com/mitchmindtree/elmesque/blob/master/examples/graphics.rs) and was able to fix it by using window.draw_size() instead of window.size() for the size of the output. I haven't tested it on other platforms, so I don't know whether it's a proper solution or not.

**Comment by bvssvni** [comment]
`.draw_size` is the size of the frame buffer while `.size` is the interior size of the window. On retina screens the draw size is twice the amount of size each direction.

**Comment by dmitry-egorov** [comment]
Yes, looks like it. The gfx_cube example uses piston_window without modifying the output size (don't know if it's even possible).

And here's the line in piston_window that seems to cause the problem: https://github.com/PistonDevelopers/piston_window/blob/master/src/lib.rs#L63

I'm hesitant to fix it myself, since I have no way to verify it's working on other platforms.

**Comment by bvssvni** [comment]
The gfx_cube example uses `win_width` and `win_height` to set up the projection matrix. I think both needs to be fixed. I'll make the changes and see if that works, or else we'll just change it back.

**Comment by dmitry-egorov** [comment]
:+1:

**Comment by bvssvni** [comment]
@dmitry-egorov Can you do a `cargo update` and see if it works now?

**Comment by dmitry-egorov** [comment]
Yes, it works fine:
![screen shot 2015-05-10 at 18 39 59](https://cloud.githubusercontent.com/assets/5902807/7554964/02656ce6-f744-11e4-8937-70c25c944668.png)

Thank you!

**Comment by bvssvni** [comment]
Closing.
