### ISSUE TITLE
crates.io's example code is too old

### ISSUE THREAD

**Issue by yumetodo** [PistonDevelopers/piston_window#225]
```rust
// example on crates.io
for e in window {
  // do something
}

// current latest readme style
while let Some(e) = window.next() {
  // do something
}
```

Why don't you update it?

**Comment by bvssvni** [comment]
Link? I only see the latest version on crates.io.

**Comment by yumetodo** [comment]
Oh...I missed that watching page is old release one.
https://crates.io/crates/piston_window/0.12.0

Thank you for your pointting.
