### ISSUE TITLE
allocator memory exhausted on Rust nightly - MacOS

### ISSUE THREAD

**Issue by sunjay** [PistonDevelopers/piston_window#227]
[Someone reported an issue](https://github.com/sunjay/turtle/issues/67) on the turtle crate and it looks like it may have something to do with piston_window on the latest Rust nightly.

Here is the information from @cuyler on the original issue in the turtle repository:

> OS: System Version: macOS 10.13.3 (17D102)
> Kernel Version: Darwin 17.4.0
> Boot Mode: Normal
> Secure Virtual Memory: Enabled
> System Integrity Protection: Enabled
> Graphics Card: Graphics: Intel Iris Plus Graphics 650, Intel Iris Plus Graphics 650, Built-In
> Cargo.lock file: [Here](https://gist.github.com/cuyler/71a6a0c2af97a60879b064846db8b6c6)
> 
> The piston_window example DOES NOT work with the rust nightly... thus probably why Turtle isn't working either.
> 
> The piston_window example fails with "allocator memory exhausted", Illegal instruction: 4

Any idea what might be going on? I don't have a Mac to test the issue, but I'm sure many other people would be willing to help out if asked.

**Comment by crazymykl** [comment]
This also occurs on both `rustc 1.26.0-beta.3 (8a75d2b50 2018-04-08)` and `rustc 1.27.0-nightly (4b9b70c39 2018-04-09)` using MacOS 10.13.4. Stable is fine.

**Comment by crazymykl** [comment]
I have made a PR to the repo where the bug was easiest fixed, but until that goes into a release, opening your `Cargo.toml` and adding:

```toml
[patch.crates-io]
pistoncore-glutin_window = { git = "https://github.com/crazymykl/glutin_window.git", branch = "fix-macos" }
```

should fix it.
