### ISSUE TITLE
Update gfx_device_gl dependency

### ISSUE THREAD

**Issue by smolck** [PistonDevelopers/piston_window#263]
Hello! After trying to run the example given [here on the main Piston repo](https://github.com/PistonDevelopers/piston#drawing-a-red-rectangle) using `piston_window` version 0.103.0 (I believe the same happens on v0.98.0, but would need to verify), I got two errors when compiling  `gfx_device_gl` (on latest nightly) that looked a bit like this:
```
failed to resolve: could not find `format args` in `core`
```

Upon further investigation, it appears to be a bug in `gfx_device_gl` version 0.16.1 (and apparently older versions since AFAIK `piston_window` version 0.103.0 uses `gfx_device_gl` version 0.15.0, right?). The issue on `gfx_device_gl` is here:
https://github.com/gfx-rs/gfx/issues/2964

The bug is fixed in `gfx_device_gl` version 0.16.2. Would it be feasible to upgrade `piston_window`'s dependency on `gfx_device_gl` to version 0.16.2 to fix this? If not, is there another way to fix this?

Thanks!

**Comment by bvssvni** [comment]
This is done automatically by `cargo update`.

**Comment by smolck** [comment]
I’m speaking of the dependency [here in Cargo.toml](https://github.com/PistonDevelopers/piston_window/blob/a1b01f52b538820d913ee2691c120f225e456a5c/Cargo.toml#L22). `cargo update` doesn’t seem to change that (at least for me). Should it?

**Comment by AgustinCB** [comment]
I have the same problem. Is this going to be updated?

**Comment by bvssvni** [comment]
Todo:

- [ ] Update "piston-gfx_texture"
- [ ] Update "piston2d-gfx_graphics"
- [ ] Update "piston_window"
