### ISSUE TITLE
Best Way to Color a Single Pixel

### ISSUE THREAD

**Issue by TheMayoras** [PistonDevelopers/piston_window#269]
I am working on a (crappy) emulator and would like to use Piston for the graphics.  Because of the way I am planning to render the graphics, I need to be able to color single points.  Is the best way to do this to use 1x1 rectangles?

**Comment by bvssvni** [comment]
The best way is to set pixel colors in an image and then update a texture before rendering. See https://github.com/PistonDevelopers/piston-examples/blob/master/src/paint.rs

**Comment by TheMayoras** [comment]
👍 perfect.  Totally missed that example!
