### ISSUE TITLE
Text rendering issue

### ISSUE THREAD

**Issue by daver32** [PistonDevelopers/piston_window#301]
Hello, I'm trying to render some text but what happens is that only the first character ever used is rendered. So in my example here, the counter starts with 1, so it will only ever render the character "1" and leave a blank space in other's stead.
 
I've tried a couple different fonts, as well as platforms (Arch Linux and Windows), but the issue persists.

Crate versions:
```toml
piston_window = "0.121.0"
piston2d-graphics = "0.41.0"
```

Here's a minimal example:

```rust
use graphics::{Graphics, Text, Transformed};
use piston_window::{PistonWindow, WindowSettings};

fn main() {
    let mut window: PistonWindow = WindowSettings::new("Title", [256, 256])
        .exit_on_esc(true)
        .resizable(false)
        .build()
        .expect("Failed to build Piston window. ");

    let mut glyphs = window
        .load_font("LiberationSans-Regular.ttf")
        .expect("Failed to load the font. ");

    let mut counter = 1;

    while let Some(event) = window.next() {
        window.draw_2d(&event, |context, graphics, _device| {
            graphics.clear_color([1.0, 1.0, 1.0, 1.0]);

            let str = format!("{}", counter);

            Text::new_color([0.0, 0.0, 0.0, 1.0], 32)
                .draw(
                    &str,
                    &mut glyphs,
                    &context.draw_state,
                    context.trans(32.0, 32.0).transform,
                    graphics,
                )
                .unwrap();

            counter += 1;
        });
    }
}

```

Is there something I'm missing or could this be a bug?

**Comment by VictorKoenders** [comment]
Duplicate of https://github.com/PistonDevelopers/piston_window/issues/258#issuecomment-514442002 (also includes a workaround that works for me)

**Comment by daver32** [comment]
> Duplicate of [#258 (comment)](https://github.com/PistonDevelopers/piston_window/issues/258#issuecomment-514442002) (also includes a workaround that works for me)

It works, thank you!
