### ISSUE TITLE
Reexport all you need at top level

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston_window#32]
```Rust
pub use piston::window::*;
pub use piston::event::*;
pub use piston::input::*;
pub use graphics::*;
```

**Comment by mitchmindtree** [comment]
Here's an example of piston_window in use in conrod's [canvas example](https://github.com/PistonDevelopers/conrod/blob/master/examples/canvas.rs).

**Comment by mitchmindtree** [comment]
Seeing as piston_window is designed for use with gfx_graphics, perhaps it should do something like this?
```Rust
type Graphics<'a> = GfxGraphics<'a, Resources, CommandBuffer, Output>;
```

**Comment by bvssvni** [comment]
I don't know if we'll stay generic, it depends on how things turn out with Vulkan back-end for Gfx.

**Comment by mitchmindtree** [comment]
Ahh of course.

Perhaps we can stay generic and call the type aliases `GlGraphics` and `GlGlyphCache` instead?

**Comment by bvssvni** [comment]
I think we can add a type alias for convenience. `GlGraphics` is used by opengl_graphics.

**Comment by mitchmindtree** [comment]
Maybe
```Rust
let window = {
        let window = GlutinWindow::new(
            OpenGL::_3_2,
            WindowSettings::new("Demo".to_string(), Size { width: 800, height: 600 })
                .exit_on_esc(true)
        );
        PistonWindow::new(Rc::new(RefCell::new(window)), piston_window::empty_app())
    };
```

Could become something like:

```Rust
let window = PistonWindow::glutin(
    WindowSettings::new("Demo", Size { width: 800.0, height: 600.0 }).exit_on_esc(true)
);
```

Or even
```Rust
let window = PistonWindow::new("Demo")
    .size(800.0, 600.0)
    .exit_on_esc(true);
```
where glutin is the default window?

**Comment by bvssvni** [comment]
Could use `G2d` as type alias.

**Comment by bvssvni** [comment]
We could make glutin the default window back-end since it is pure Rust. This will require some extra dependencies, but that might be acceptable.

**Comment by mitchmindtree** [comment]
```Rust
fn main() {
    for event in PistonWindow::new("Demo").size(800.0, 600.0).exit_on_esc(true) {
        // Get creative!
    }
}
```

**Comment by bvssvni** [comment]
What about `PistonGraphics` and `PistonGlyphCache`?

**Comment by mitchmindtree** [comment]
Hmm I think I prefer `G2d` to `PistonGraphics`.

Maybe we could alias `GlyphCache` to `Glyphs`?

**Comment by bvssvni** [comment]
Good idea!

**Comment by bvssvni** [comment]
I have updated the PR.

**Comment by bvssvni** [comment]
I updated the window back-ends using the `From` trait. It now looks like this:

```Rust
    let window: PistonWindow = WindowSettings::new("Hello Piston!", [640, 480])
        .exit_on_esc(true)
        .into();
```
