### ISSUE TITLE
A more involved example

### ISSUE THREAD

**Issue by TheNeikos** [PistonDevelopers/piston_window#59]
Would it be possible that the project becomes an example that is a bit more involved as the current one?

I am particularly interested in the `app()` method of `PistonWindow`.

I looked through the piston-examples and don't seem to find something.

**Comment by bvssvni** [comment]
There are more examples here, but none of them uses the `app()` method https://github.com/pistondevelopers/piston-examples.

**Comment by bvssvni** [comment]
You can do things like this:

```Rust
fn start_scene() -> Rc<RefCell<Scene>> { ... }

let scene = window.app(start_scene());
scene.app.borrow_mut().update();
```

**Comment by TheNeikos** [comment]
Hm, perhaps I am completely misunderstanding the use-case, I was thinking of it as something like this:

```rust
struct ApplicationState {
    scenes: Vec<Box<Scene>>
}

trait Scene {
    fn update(...);
    fn draw(...);
}
```

And then use it on the `last` in the scene stack until it breaks that loop or starts a loop itself.

I might be completely wrong as well, I'm not necessarily new to programming, but I don't have any experience in game programming.

**Comment by bvssvni** [comment]
The example I showed was just to show that you could store something in the `.app` field. Not intended as a general recommended way of programming games.

**Comment by TheNeikos** [comment]
Okay, so it is just to store some state and not to be used integrally?

**Comment by bvssvni** [comment]
You can swap it and store application state there to pass one argument around. That is all.

**Comment by TheNeikos** [comment]
Alright, thanks!
