### ISSUE TITLE
GfxStream hardcoded to gfx_device_gl::Output

### ISSUE THREAD

**Issue by TheNeikos** [PistonDevelopers/piston_window#72]
I wanted to give a function a PistonWindow and somehow get the drawing it does into a framebuffer I can then handle like a texture. 

Happily there exists a `Plane` struct that seems to do just that. However, `PistonWindow` expects a `GfxStream` in it's stream argument, so using `StreamFactory::create_stream` one can make one.

This is where things go wrong, `GfxStream` aliases to an OwnedStream that is bound to the `Output` *struct* rather than Trait, which means I cannot give it a `Plane` for example.

If I am not supposed to do it anyway, is there another way to get a PistonWindow instance to draw to a texture?

```rust
            let draw_size = window.window.borrow().draw_size();

            let tex = window.factory.borrow_mut().create_texture(TextureInfo {
                width: draw_size.width as u16,
                height: draw_size.height as u16,
                depth: 1u16,
                levels: 0,
                kind: Kind::D2,
                format: Format::Unsigned(Components::RGBA, 8, IntSubType::Normalized)
            }).unwrap();

            let plane = Plane::Texture(tex, 0, None);

            let stream = window.factory.borrow_mut().create_stream(plane);

            let mut window = window.clone();
            window.stream = Rc::new(RefCell::new(stream));

```

**Comment by bvssvni** [comment]
Can you store the new stream in the `.app` field instead?

```Rust
let window = window.app_by_value(stream);
```

**Comment by TheNeikos** [comment]
Sure, but then I lose the simpleness of just doing `draw_2d` or `draw_3d`.

**Comment by bvssvni** [comment]
I think this can be closed now that Gfx has changed design.
