### ISSUE TITLE
`thread '<main>' has overflowed its stack`

### ISSUE THREAD

**Issue by quadrupleslap** [PistonDevelopers/piston_window#77]
I tried adding this to my `cargo.toml`. It gave me the following error:

```
thread '<main>' has overflowed its stack
Illegal instruction: 4
```

Using git didn't fix the problem either.

**Comment by bvssvni** [comment]
Could you post OS and `rustc -V, cargo -V`?

**Comment by quadrupleslap** [comment]
Operating System: OS X Yosemite 10.10.2 (14C109)

```sh
$ cargo run -v
    Updating registry `https://github.com/rust-lang/crates.io-index`

thread '<main>' has overflowed its stack
Illegal instruction: 4

$ rustc -V
rustc 1.3.0-nightly (4dfe7a16c 2015-07-30)

$ cargo -V
cargo 0.4.0-nightly (e0a82d6 2015-07-29) (built 2015-07-30)
```

**Comment by dobrite** [comment]
Getting this randomly. Most of the time `cargo build` works, but maybe 25% of the time I get the error. Trying immediately without changing anything sometimes works, sometimes errors, but eventually will work.

Same rust/cargo as above.

```
OS: OS X Yosemite 10.10.3 (14D136)

$ rustc -V
rustc 1.3.0-nightly (4dfe7a16c 2015-07-30)
$ cargo -V
cargo 0.4.0-nightly (e0a82d6 2015-07-29) (built 2015-07-30)
```

**Comment by bvssvni** [comment]
Getting this on `cargo update` for https://github.com/pistondevelopers/piston-examples:

```
$rustc -V
rustc 1.3.0-nightly (4dfe7a16c 2015-07-30)
$cargo -V
cargo 0.4.0-nightly (e0a82d6 2015-07-29) (built 2015-07-30)
```

**Comment by bvssvni** [comment]
Seems to be an issue with Cargo. Getting the same error on

```
cargo 0.4.0-nightly (1b902d4 2015-08-03) (built 2015-08-03)
```

**Comment by bvssvni** [comment]
Opened an issue https://github.com/rust-lang/cargo/issues/1875

**Comment by bvssvni** [comment]
I installed Rust 1.1 and got it working.

**Comment by quadrupleslap** [comment]
Somehow started working again for me. Might be an update in Rust, or it could be an update in `piston_window`.

**Comment by bvssvni** [comment]
It was fixed by https://github.com/rust-lang/cargo/pull/1887. Closing.

**Comment by bvssvni** [comment]
Rust nightly has not been updated yet, but I expect it to work tomorrow.
