### ISSUE TITLE
can't use OwnedStream::present with stream field in PistonWindow?

### ISSUE THREAD

**Issue by olsonjeffery** [PistonDevelopers/piston_window#81]
Hi,

I'm trying to take a dependency on `piston_window` for an existing project (so I can easily integrate with `conrod`) that I have that has been using straight-up `gfx-rs` and `glutin` (I'm doing low-level OpenGL mesh/shader stuff that I want to keep). I've changed my initialization code over to use `PistonWindow` and am working on adapting individual uses of `factory`, `stream` and `device` (the items returned from a successful call to `gfx_window_glutin::init()`)

Here's the build error that I'm encountering, should be self-evident:

```
ash-3.2$ cargo build
   Compiling game-proj v0.0.1 (file:///Users/jeff/src/game-proj)
src/client/main.rs:120:28: 120:37 error: no method named `present` found for type `core::cell::RefMut<'_, gfx::extra::stream::OwnedStream<gfx_device_gl::Device, gfx_device_gl::factory::Output>>` in the current scope
src/client/main.rs:120     (*stream).borrow_mut().present((*device).borrow());
                                                  ^~~~~~~~~
src/client/main.rs:120:28: 120:37 note: the method `present` exists but the following trait bounds were not satisfied: `gfx_device_gl::factory::Output : gfx::extra::stream::Window<gfx_device_gl::Resources>`
error: aborting due to previous error
Could not compile `game-proj`.
```

I imagine this is something related to what the compiler thinks that instance is. I assume the solution is something involving coercion/casthing.. but not sure what the magic password is.

Any tips on how to proceed, here? Let me know if you need to see more code.

Thanks.

**Comment by bvssvni** [comment]
Seems to be that the output in `PistonWindow` does not implement `Window` https://github.com/gfx-rs/gfx/blob/d887d796ccd1e05759d3f7cf1e0755846f00913c/src/core/src/extra/stream.rs#L145

Do you use the piston event loop? In that case, the event iterator will swap the buffers for you, so you only need `.flush`.

**Comment by bvssvni** [comment]
Closed because outdated.
